 language: scala
 scala:
   - "2.10.4"
   - "2.11.4"
 jdk:
   - oraclejdk7
   - openjdk7
   - oraclejdk8
 addons:
  postgresql: "9.3"
 script: "sbt clean coverage test"
 after_success: "sbt coveralls"
 before_script:
  - sudo ./init.sh